# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/on7xelte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/on7xelte/proprietary/app/mcRegistry/00060308060501020000000000000000.tlbin:system/app/mcRegistry/00060308060501020000000000000000.tlbin \
    vendor/samsung/on7xelte/proprietary/app/mcRegistry/ffffffff000000000000000000000004.tlbin:system/app/mcRegistry/ffffffff000000000000000000000004.tlbin \
    vendor/samsung/on7xelte/proprietary/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
    vendor/samsung/on7xelte/proprietary/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
    vendor/samsung/on7xelte/proprietary/app/mcRegistry/ffffffff000000000000000000000016.tlbin:system/app/mcRegistry/ffffffff000000000000000000000016.tlbin \
    vendor/samsung/on7xelte/proprietary/app/mcRegistry/ffffffff000000000000000000000019.tlbin:system/app/mcRegistry/ffffffff000000000000000000000019.tlbin \
    vendor/samsung/on7xelte/proprietary/app/mcRegistry/ffffffff000000000000000000000045.tlbin:system/app/mcRegistry/ffffffff000000000000000000000045.tlbin \
    vendor/samsung/on7xelte/proprietary/app/mcRegistry/ffffffff000000000000000000000059.tlbin:system/app/mcRegistry/ffffffff000000000000000000000059.tlbin \
    vendor/samsung/on7xelte/proprietary/app/mcRegistry/ffffffff000000000000000000000060.tlbin:system/app/mcRegistry/ffffffff000000000000000000000060.tlbin \
    vendor/samsung/on7xelte/proprietary/app/mcRegistry/ffffffffd00000000000000000000004.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
    vendor/samsung/on7xelte/proprietary/bin/prepare_param.sh:system/bin/prepare_param.sh \
    vendor/samsung/on7xelte/proprietary/bin/srm.bin:system/bin/srm.bin \
    vendor/samsung/on7xelte/proprietary/lib/android.hardware.radio@1.1.so:system/lib/android.hardware.radio@1.1.so \
    vendor/samsung/on7xelte/proprietary/lib/hw/camera.vendor.universal7870.so:system/lib/hw/camera.vendor.universal7870.so \
    vendor/samsung/on7xelte/proprietary/lib/hw/gralloc.exynos5.so:system/lib/hw/gralloc.exynos5.so \
    vendor/samsung/on7xelte/proprietary/lib/libExynosOMX_Core.so:system/lib/libExynosOMX_Core.so \
    vendor/samsung/on7xelte/proprietary/lib/libExynosOMX_Resourcemanager.so:system/lib/libExynosOMX_Resourcemanager.so \
    vendor/samsung/on7xelte/proprietary/lib/libaudio-ril.so:system/lib/libaudio-ril.so \
    vendor/samsung/on7xelte/proprietary/lib/libexynoscamera.so:system/lib/libexynoscamera.so \
    vendor/samsung/on7xelte/proprietary/lib/libexynoscamera3.so:system/lib/libexynoscamera3.so \
    vendor/samsung/on7xelte/proprietary/lib/liboemcrypto.so:system/lib/liboemcrypto.so \
    vendor/samsung/on7xelte/proprietary/lib/libseccameracore.so:system/lib/libseccameracore.so \
    vendor/samsung/on7xelte/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/on7xelte/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/on7xelte/proprietary/lib/libsensorlistener.so:system/lib/libsensorlistener.so \
    vendor/samsung/on7xelte/proprietary/lib/libsensorservice.so:system/lib/libsensorservice.so \
    vendor/samsung/on7xelte/proprietary/lib/libstagefright_hdcp.so:system/lib/libstagefright_hdcp.so \
    vendor/samsung/on7xelte/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/samsung/on7xelte/proprietary/lib/omx/libOMX.Exynos.AVC.Decoder.so:system/lib/omx/libOMX.Exynos.AVC.Decoder.so \
    vendor/samsung/on7xelte/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/on7xelte/proprietary/lib/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib/omx/libOMX.Exynos.HEVC.Decoder.so \
    vendor/samsung/on7xelte/proprietary/lib/omx/libOMX.Exynos.HEVC.Encoder.so:system/lib/omx/libOMX.Exynos.HEVC.Encoder.so \
    vendor/samsung/on7xelte/proprietary/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Decoder.so \
    vendor/samsung/on7xelte/proprietary/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Encoder.so \
    vendor/samsung/on7xelte/proprietary/lib/omx/libOMX.Exynos.VP8.Decoder.so:system/lib/omx/libOMX.Exynos.VP8.Decoder.so \
    vendor/samsung/on7xelte/proprietary/lib/omx/libOMX.Exynos.VP8.Encoder.so:system/lib/omx/libOMX.Exynos.VP8.Encoder.so \
    vendor/samsung/on7xelte/proprietary/lib/omx/libOMX.Exynos.WMV.Decoder.so:system/lib/omx/libOMX.Exynos.WMV.Decoder.so \
    vendor/samsung/on7xelte/proprietary/vendor/app/mcRegistry/07010000000000000000000000000000.tlbin:system/vendor/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/samsung/on7xelte/proprietary/vendor/app/mcRegistry/07060000000000000000000000000000.tlbin:system/vendor/app/mcRegistry/07060000000000000000000000000000.tlbin \
    vendor/samsung/on7xelte/proprietary/vendor/app/mcRegistry/08130000000000000000000000000000.tlbin:system/vendor/app/mcRegistry/08130000000000000000000000000000.tlbin \
    vendor/samsung/on7xelte/proprietary/vendor/app/mcRegistry/FFFFFFFF000000000000000000000001.drbin:system/vendor/app/mcRegistry/FFFFFFFF000000000000000000000001.drbin \
    vendor/samsung/on7xelte/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000005.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
    vendor/samsung/on7xelte/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000a.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
    vendor/samsung/on7xelte/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000b.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000000b.tlbin \
    vendor/samsung/on7xelte/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000f.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
    vendor/samsung/on7xelte/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000012.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000012.tlbin \
    vendor/samsung/on7xelte/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000013.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000013.tlbin \
    vendor/samsung/on7xelte/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000017.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000017.tlbin \
    vendor/samsung/on7xelte/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000002e.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000002e.tlbin \
    vendor/samsung/on7xelte/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000002f.tlbin:system/vendor/app/mcRegistry/ffffffff00000000000000000000002f.tlbin \
    vendor/samsung/on7xelte/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000030.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000030.tlbin \
    vendor/samsung/on7xelte/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000038.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000038.tlbin \
    vendor/samsung/on7xelte/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000041.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000041.tlbin \
    vendor/samsung/on7xelte/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000073.tlbin:system/vendor/app/mcRegistry/ffffffff000000000000000000000073.tlbin \
    vendor/samsung/on7xelte/proprietary/vendor/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:system/vendor/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
    vendor/samsung/on7xelte/proprietary/vendor/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin:system/vendor/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin \
    vendor/samsung/on7xelte/proprietary/vendor/app/mcRegistry/ffffffffd00000000000000000000016.tlbin:system/vendor/app/mcRegistry/ffffffffd00000000000000000000016.tlbin \
    vendor/samsung/on7xelte/proprietary/vendor/bin/hw/gpsd:system/vendor/bin/hw/gpsd \
    vendor/samsung/on7xelte/proprietary/vendor/bin/hw/rild:system/vendor/bin/hw/rild \
    vendor/samsung/on7xelte/proprietary/vendor/bin/mcDriverDaemon:system/vendor/bin/mcDriverDaemon \
    vendor/samsung/on7xelte/proprietary/vendor/etc/gnss/ca.pem:system/vendor/etc/gnss/ca.pem \
    vendor/samsung/on7xelte/proprietary/vendor/etc/plmn_delta.bin:system/vendor/etc/plmn_delta.bin \
    vendor/samsung/on7xelte/proprietary/vendor/etc/plmn_delta_hktw.bin:system/vendor/etc/plmn_delta_hktw.bin \
    vendor/samsung/on7xelte/proprietary/vendor/etc/plmn_se13.bin:system/vendor/etc/plmn_se13.bin \
    vendor/samsung/on7xelte/proprietary/vendor/etc/wifi/bcmdhd_apsta.bin:system/vendor/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/on7xelte/proprietary/vendor/etc/wifi/bcmdhd_mfg.bin:system/vendor/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/on7xelte/proprietary/vendor/etc/wifi/bcmdhd_sta.bin:system/vendor/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/on7xelte/proprietary/vendor/etc/wifi/cred.conf:system/vendor/etc/wifi/cred.conf \
    vendor/samsung/on7xelte/proprietary/vendor/etc/wifi/nvram.txt:system/vendor/etc/wifi/nvram.txt \
    vendor/samsung/on7xelte/proprietary/vendor/firmware/bcm43438A1_V0068.0286.hcd:system/vendor/firmware/bcm43438A1_V0068.0286.hcd \
    vendor/samsung/on7xelte/proprietary/vendor/firmware/fimc_is_lib.bin:system/vendor/firmware/fimc_is_lib.bin \
    vendor/samsung/on7xelte/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/samsung/on7xelte/proprietary/vendor/firmware/setfile_4h5yc.bin:system/vendor/firmware/setfile_4h5yc.bin \
    vendor/samsung/on7xelte/proprietary/vendor/firmware/setfile_imx258.bin:system/vendor/firmware/setfile_imx258.bin \
    vendor/samsung/on7xelte/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/hw/gps.default.so:system/vendor/lib/hw/gps.default.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/hw/sensors.universal7870.so:system/vendor/lib/hw/sensors.universal7870.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libMcClient.so:system/vendor/lib/libMcClient.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libMcRegistry.so:system/vendor/lib/libMcRegistry.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libOpenCv.so:system/vendor/lib/libOpenCv.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libSEF.so:system/vendor/lib/libSEF.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libbauthserver.so:system/vendor/lib/libbauthserver.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libbauthtzcommon.so:system/vendor/lib/libbauthtzcommon.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libegis_fp_normal_sensor_test.so:system/vendor/lib/libegis_fp_normal_sensor_test.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libfloatingfeature.so:system/vendor/lib/libfloatingfeature.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libreference-ril.so:system/vendor/lib/libreference-ril.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libril.so:system/vendor/lib/libril.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/librilutils.so:system/vendor/lib/librilutils.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libsec-ril-dsds.so:system/vendor/lib/libsec-ril-dsds.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libsec-ril.so:system/vendor/lib/libsec-ril.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libsecnativefeature.so:system/vendor/lib/libsecnativefeature.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libsomp.so:system/vendor/lib/libsomp.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libstainkiller.so:system/vendor/lib/libstainkiller.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libsynaFpSensorTestNwd.so:system/vendor/lib/libsynaFpSensorTestNwd.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libvndsecril-client.so:system/vendor/lib/libvndsecril-client.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libwrappergps.so:system/vendor/lib/libwrappergps.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/vendor.samsung.hardware.radio.channel@1.0_vendor.so:system/vendor/lib/vendor.samsung.hardware.radio.channel@1.0_vendor.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/vendor.samsung.hardware.radio.secoemhook@1.0_vendor.so:system/vendor/lib/vendor.samsung.hardware.radio.secoemhook@1.0_vendor.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/vendor.samsung.hardware.radio@1.1_vendor.so:system/vendor/lib/vendor.samsung.hardware.radio@1.1_vendor.so
# Create Mali links for Vulkan and OpenCL
PRODUCT_PACKAGES += libGLES_mali
